### ISSUE TITLE
`parachain-template-node` does not work with `polkadot-v0.9.36`

### ISSUE THREAD

**Issue by RomarQ** [paritytech/cumulus#2043]
I have been trying to update the parachain dependencies from `v0.9.29` to `v0.9.36`, but unfortunately, I was not able to successfully do it. After a few failed attempts I decided to try the `parachain-template-node`, which seems to not be working as well.

After 8 blocks I reach the following condition: `VRF verification failed: EquationFalse`.

I have also tried version `v0.9.33` without success. 

Does anyone know the root of the issue?

I have tried tried it against a local `rococo`  instance.

**Logs:**

```log
2022-12-26 15:11:42.048 DEBUG tokio-runtime-worker runtime::mmr::offchain: [Relaychain] offchain db set: pos 55 parent_hash 0x7eccb7950d91f6aed8f1f89a2942bb8ffad9ae3947f873d03b308676e5c63476 key [12, 109, 109, 114, 55, 0, 0, 0, 0, 0, 0, 0, 126, 204, 183, 149, 13, 145, 246, 174, 216, 241, 248, 154, 41, 66, 187, 143, 250, 217, 174, 57, 71, 248, 115, 208, 59, 48, 134, 118, 229, 198, 52, 118]    
2022-12-26 15:11:42.048 DEBUG tokio-runtime-worker runtime::inclusion-inherent: [Relaychain] [enter_inner] parent_header=0x7eccb7950d91f6aed8f1f89a2942bb8ffad9ae3947f873d03b308676e5c63476 bitfields.len(): 4, backed_candidates.len(): 1, disputes.len(): 0    
2022-12-26 15:11:42.052 DEBUG tokio-runtime-worker runtime::system: [Relaychain] [30] 0 extrinsics, length: 1179 (normal 0%, op: 0%, mandatory 0%) / normal weight:Weight(ref_time: 0, proof_size: 0) (0%) op weight Weight(ref_time: 0, proof_size: 0) (0%) / mandatory weight Weight(ref_time: 14392096822, proof_size: 0) (0%)    
2022-12-26 15:11:42.055  INFO tokio-runtime-worker substrate: [Relaychain] ✨ Imported #30 (0x593a…6105)    
2022-12-26 15:11:42.056 DEBUG tokio-runtime-worker parachain::collator-protocol: [Relaychain] Removing relay parent because our view changed. relay_parent=0x7eccb7950d91f6aed8f1f89a2942bb8ffad9ae3947f873d03b308676e5c63476
2022-12-26 15:11:42.056 DEBUG tokio-runtime-worker parachain::collator-protocol: [Relaychain] Collation was requested. candidate_hash=0x912d7cd4aa5c84877ca55d783146f6f04e8bed85bdce9bc916b52d468cd2cdb3 pov_hash=0xcfa30f1c3fe44025f6ccb8161fee9c719663572965b1cea7cc6e1d7f64779157 traceID=192974244615332473342209119479849744112
2022-12-26 15:11:42.058 DEBUG tokio-runtime-worker parachain::availability-store: [Relaychain] Candidate backed candidate_hash=0x912d7cd4aa5c84877ca55d783146f6f04e8bed85bdce9bc916b52d468cd2cdb3 traceID=192974244615332473342209119479849744112
2022-12-26 15:11:42.059 DEBUG tokio-runtime-worker parachain::approval-voting: [Relaychain] Imported new block. block_number=30 block_hash=0x593a21c764a04bf1751daaf0e86cae0a19a7b344b686bd48a8ba44f0b4d96105 num_candidates=0
2022-12-26 15:11:42.059 DEBUG tokio-runtime-worker parachain::approval-distribution: [Relaychain] Got new blocks [(0x593a21c764a04bf1751daaf0e86cae0a19a7b344b686bd48a8ba44f0b4d96105, 30)]
2022-12-26 15:11:44.909 DEBUG tokio-runtime-worker parachain::chain-selection: [Relaychain] Prepared 0 stagnant entries for pruning up_to=1671977504 min_ts=0 max_ts=0
2022-12-26 15:11:44.915  INFO tokio-runtime-worker substrate: [Relaychain] 💤 Idle (4 peers), best: #30 (0x593a…6105), finalized #27 (0xae82…2fae), ⬇ 1.9kiB/s ⬆ 1.8kiB/s    
2022-12-26 15:11:44.922  INFO tokio-runtime-worker substrate: [Parachain] 💤 Idle (0 peers), best: #9 (0x8df1…8d29), finalized #8 (0x4bce…04d4), ⬇ 0 ⬆ 0    
2022-12-26 15:11:47.477 DEBUG tokio-runtime-worker parachain::approval-voting: [Relaychain] Block finalized block_hash=0x10b4d09077d8de9b94fb7a41cbe72ebeed6da2eeee5297a28c7344b3cf7e8e7b block_number=28
2022-12-26 15:11:47.477 DEBUG tokio-runtime-worker parachain::collator-protocol: [Relaychain] Removing relay parent because our view changed. relay_parent=0xbf9581cb09c67e63c55afad492724befa3f131e964613f28655a404a6bccc7b5
2022-12-26 15:11:48.044  WARN tokio-runtime-worker sync: [Relaychain] 💔 Verification failed for block 0xff74f3ac6cc368557297f06f0fdde5398693d342a796a30ae4d2152135d9fd2f received from peer: 12D3KooWPKzmmE2uYgF3z13xjpbFTp63g9dZFag8pG6MgnpSLF4S, "VRF verification failed: EquationFalse"    
2022-12-26 15:11:48.060  WARN tokio-runtime-worker sync: [Relaychain] 💔 Verification failed for block 0xff74f3ac6cc368557297f06f0fdde5398693d342a796a30ae4d2152135d9fd2f received from peer: 12D3KooWKM1HeSv61ryZwAiBTZnqmass5pYM48k9Z7obzhTbnphm, "VRF verification failed: EquationFalse"    
2022-12-26 15:11:48.064  WARN tokio-runtime-worker sync: [Relaychain] 💔 Verification failed for block 0xff74f3ac6cc368557297f06f0fdde5398693d342a796a30ae4d2152135d9fd2f received from peer: 12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm, "VRF verification failed: EquationFalse"    
2022-12-26 15:11:48.937 DEBUG tokio-runtime-worker parachain::collator-protocol: [Relaychain] Timeout hit, sent a connection request. Disconnected from all validators = true timeout=12s
2022-12-26 15:11:48.937 DEBUG tokio-runtime-worker parachain::validator-discovery: [Relaychain] New ConnectToValidators request peer_set=Collation requested=0 failed_to_resolve=0
2022-12-26 15:11:48.937 DEBUG tokio-runtime-worker parachain::validator-discovery: [Relaychain] New ConnectToValidators resolved request peer_set=Collation num_peers=0 removed=1
2022-12-26 15:11:48.937 DEBUG tokio-runtime-worker parachain::network-bridge-rx: [Relaychain] action="PeerDisconnected" peer_set=Collation peer=PeerId("12D3KooWKM1HeSv61ryZwAiBTZnqmass5pYM48k9Z7obzhTbnphm")
2022-12-26 15:11:49.909 DEBUG tokio-runtime-worker parachain::chain-selection: [Relaychain] Prepared 0 stagnant entries for pruning up_to=1671977509 min_ts=0 max_ts=0
2022-12-26 15:11:49.915  INFO tokio-runtime-worker substrate: [Relaychain] 💤 Idle (0 peers), best: #30 (0x593a…6105), finalized #28 (0x10b4…8e7b), ⬇ 5.0kiB/s ⬆ 2.3kiB/s    
2022-12-26 15:11:49.923  INFO tokio-runtime-worker substrate: [Parachain] 💤 Idle (0 peers), best: #9 (0x8df1…8d29), finalized #8 (0x4bce…04d4), ⬇ 0 ⬆ 0    
2022-12-26 15:11:53.048  WARN tokio-runtime-worker sync: [Relaychain] 💔 Verification failed for block 0xff74f3ac6cc368557297f06f0fdde5398693d342a796a30ae4d2152135d9fd2f received from peer: 12D3KooWPKzmmE2uYgF3z13xjpbFTp63g9dZFag8pG6MgnpSLF4S, "VRF verification failed: EquationFalse"    
2022-12-26 15:11:53.063  WARN tokio-runtime-worker sync: [Relaychain] 💔 Verification failed for block 0xff74f3ac6cc368557297f06f0fdde5398693d342a796a30ae4d2152135d9fd2f received from peer: 12D3KooWKM1HeSv61ryZwAiBTZnqmass5pYM48k9Z7obzhTbnphm, "VRF verification failed: EquationFalse"    
2022-12-26 15:11:54.909 DEBUG tokio-runtime-worker parachain::chain-selection: [Relaychain] Prepared 0 stagnant entries for pruning up_to=1671977514 min_ts=0 max_ts=0
```

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/issues/12752

We have fixed this some time ago 🤔🤔

Are you really sure that you are using 0.9.36 for the relay chain and the parachain?

**Comment by bkchr** [comment]
Cc @davxy

**Comment by RomarQ** [comment]
> [paritytech/substrate#12752](https://github.com/paritytech/substrate/issues/12752)
> 
> We have fixed this some time ago thinkingthinking
> 
> Are you really sure that you are using 0.9.36 for the relay chain and the parachain?

Yes, I downloaded the artifact from https://github.com/paritytech/polkadot/releases/tag/v0.9.36

**Comment by davxy** [comment]
Ok you're running polkadot 0.9.36 for your relay chain nodes. But the fault that you see comes from the relay chain node embedded within the parachain collator.  You also have to update the relay chain dependencies in your cumulus project.

Try to checkout the tag `v0.9.360` in cumulus

In your `parachain-template/node/Cargo.toml` you should see something like...

```
...
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
...                                                                ^^^^^^^^^^^^
```

**Comment by RomarQ** [comment]
I am not using an embedded relay chain on the collator. The setup has 4 relay validators and it works well on v0.9.29.

The only differences between `release-v0.9.360` and `polkadot-v0.9.36` are the following:

![image](https://user-images.githubusercontent.com/22591718/209572562-b6ed641b-c385-45c7-a7d3-e59d8bc7ae2e.png)

**Comment by davxy** [comment]
The logs that you've pasted are coming from the collator binary.

The lines with `[RelayChain]` comes from the relay chain "embedded" node that ships with the collator. Is not something that you choose to run or not, is always there to gather informations from the relay chain. 

Can you please print the lines in `parachain-template/node/Cargo.toml`? For example the one for `sc-consensus`

**Comment by RomarQ** [comment]
Got it, by embedded I was assuming something like `substrate-node-template`.

```toml
[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
log = "0.4.17"
codec = { package = "parity-scale-codec", version = "3.0.0" }
serde = { version = "1.0.151", features = ["derive"] }
jsonrpsee = { version = "0.16.2", features = ["server"] }

# runtime stuff

# Substrate
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-network-common = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-sysinfo = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
try-runtime-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.36" }

# Polkadot
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.36" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.36" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.36" }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.36" }

# Cumulus
cumulus-client-cli = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.36" }
cumulus-client-consensus-aura = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.36" }
cumulus-client-consensus-common = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.36" }
cumulus-client-network = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.36" }
cumulus-client-service = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.36" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.36" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.36" }
cumulus-relay-chain-inprocess-interface = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.36" }
cumulus-relay-chain-interface = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.36" }
cumulus-relay-chain-rpc-interface = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.36" }
cumulus-relay-chain-minimal-node = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.36" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
```

**Comment by RomarQ** [comment]
You can use https://github.com/paritytech/cumulus/tree/polkadot-v0.9.36/parachain-template as reproducible example.

**Comment by davxy** [comment]
I'm trying it right now. But for me works just fine.

Can you give me more details about your setup?

1. Have you started your network from scratch?
2. How you started the network?

**Comment by davxy** [comment]
Can you try to remove the DB from the collator and restart it?

In some of the old version there was a bug that ended up saving incorrectly some internal structures used by babe. Thus if it was already corrupted, it can't be recovered just by restarting the network with the new version, should be regenerated.

**Comment by RomarQ** [comment]
The issue only appears after block 9.

1. Download the relay chain binary from https://github.com/paritytech/polkadot/releases/tag/v0.9.36
2. Clone branch `polkadot-v0.9.36` at https://github.com/paritytech/cumulus
3. Compile it with `cargo build --release -p parachain-template-node`
4. Then move all these binaries to a `zombinet` folder
5. And spawn the network with `./zombienet-linux spawn config.toml` 

`config.toml`
```toml
[settings]
provider="native"

[relaychain]
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  command = "polkadot"
  ws_port = 9944

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  command = "polkadot"

  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  command = "polkadot"

  [[relaychain.nodes]]
  name = "dave"
  validator = true
  command = "polkadot"

[[parachains]]
id = 2001
chain = "local"
cumulus_based = true

  [parachains.collator]
  name = "some-collator"
  command = "parachain-template-node"
  ws_port = 8802
  rpc_port = 8082
  args = [ "-lparachain=debug,runtime=debug" ]
```

**Comment by RomarQ** [comment]
> Can you try to remove the DB from the collator and restart it from scratch?
> 
> In some of the old version there was a bug that ended up saving incorrectly some internal structures used by babe. Thus if it was already corrupted, it can't be recovered just by restarting the network with the new version, should be regenerated.

The example above does a fresh deployment. 

I will try to dig a bit more on my side, since you are saying that it works fine on your setup. Will try without zombinet.

**Comment by davxy** [comment]
Going to try your zombienet setup. Feedback soon

**Comment by davxy** [comment]
Done exactly the same steps you've described and works fine.

Please also double check that you are using the right binaries and that are updated.

In the `config.toml` that you've pasted you are using `polkadot` and `parachain-template-node` from a folder that should be in your `PATH` env var, maybe are not the one you've just built? Just an hypothesis

The error that you are experiencing is 100% equal to the one we've fixed and doesn't trigger here.
(i.e. triggers when importing block 31 in the embedded relay chain, the one that signals that epoch 2 is starting).
That's why looks suspicious.

Please double check everything :-)

**Comment by RomarQ** [comment]
Did it produce block number 10?

**Comment by davxy** [comment]
yes

**Comment by RomarQ** [comment]
> yes

Ok, I will have another look at my setup. Thanks.

**Comment by davxy** [comment]
https://pastebin.com/5fKE2Qj7

**Comment by RomarQ** [comment]
The error seems to come from the relay chain. I have even compiled the node locally.

Will move the issue to the substrate repository.

```sh
Version: 0.9.36-dc25abc712e

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/alloc/src/boxed.rs:2032:9
      std::panicking::rust_panic_with_hook
             at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:577:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/core/src/panicking.rs:64:14
   6: alloc::raw_vec::capacity_overflow
             at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/alloc/src/raw_vec.rs:518:5
   7: <alloc::vec::Vec<T,A> as core::clone::Clone>::clone
   8: <alloc::vec::Vec<T,A> as core::clone::Clone>::clone
   9: <alloc::vec::Vec<T,A> as core::clone::Clone>::clone
  10: <alloc::vec::Vec<T,A> as core::clone::Clone>::clone
  11: <sc_consensus_epochs::EpochChanges<Hash,Number,E> as core::clone::Clone>::clone
  12: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
  13: <alloc::boxed::Box<dyn sc_consensus::block_import::BlockImport<B>+Error = sp_consensus::error::Error+Transaction = Transaction+core::marker::Send+core::marker::Sync> as sc_consensus::block_import::BlockImport<B>>::import_block::{{closure}}
  14: futures_util::future::future::FutureExt::poll_unpin
  15: sc_consensus::import_queue::basic_queue::BlockImportWorker<B>::new::{{closure}}
  16: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  17: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  18: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  19: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  20: tokio::runtime::park::CachedParkThread::block_on
  21: tokio::runtime::handle::Handle::block_on
  22: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  23: tokio::runtime::task::core::Core<T,S>::poll
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: tokio::runtime::blocking::pool::Inner::run
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/alloc/src/boxed.rs:2000:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/alloc/src/boxed.rs:2000:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/sys/unix/thread.rs:108:17
  29: <unknown>
  30: <unknown>


Thread 'tokio-runtime-worker' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

```

**Comment by bkchr** [comment]
@RomarQ just for posterity, could you tell us what the issue was on your side or what you have done to fix it?

**Comment by RomarQ** [comment]
I have not been able to fix it. My issue seems to come from the relay chain, it cannot produce more than 30 blocks when using `rococo-local`. Works fine when using `polkadot-local` and used to work fine with `rococo-local` on `v0.9.29`.

Later today I will have a better look at this and create an issue on `polkadot` repository if I am not able to make it work.

**Comment by bkchr** [comment]
> it cannot produce more than 30 blocks when using `rococo-local`

With a parachain registered or without?

For rococo local we have a really short session time of 1 minute afair, but this shouldn't influence this 🤔

**Comment by RomarQ** [comment]
Even without.

**Comment by RomarQ** [comment]
In the logs bellow I am using `v0.9.33`, but it is the same for `v0.9.36`.

[alice.log](https://github.com/paritytech/cumulus/files/10308349/alice.log)
[bob.log](https://github.com/paritytech/cumulus/files/10308338/bob.log)

**Comment by davxy** [comment]
Strange that given the same zombienet config and same binaries you experience this fault and doesn't reproduce for me.

I saw you precendently posted a log, now removed, where there was a panic for what looked like an OOM error or something like that.

Can I ask you test machine specs? (Memory)

**Comment by RomarQ** [comment]
> Strange that given the same zombienet config and same binaries you experience this fault and doesn't reproduce for me.
> 
> I saw you precendently posted a log, now removed, where there was a panic for what looked like an OOM error or something like that.
> 
> Can I ask your test machine specs? (Memory)

32GB of memory
16 CPU cores

**Comment by davxy** [comment]
Few more question. Because reproduction is resolution 😀
1. is that systematic? I mean, does it happens in every run?
2. can you paste **exactly** the minimal zombienet config that triggers the fault?
3. Does it triggers if you don't include the parachains in the zombienet network config? (I.e. if you only run  relay chain)

**Comment by RomarQ** [comment]
> Few more questions. Because reproduction is resolution grinning
> 
> 1. is that systematic? I mean, does it happens in every run?
> 2. can you paste **exactly** the minimal zombienet config that triggers the fault?
> 3. Does it triggers if you don't include the parachains in the zombienet network config? (I.e. if you only run  relay chain)
>    Thank you

1. Yes, it is systematic.
2. Sure 

```toml
[settings]
provider="native"

[relaychain]
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2001
chain = "local"
cumulus_based = true

  [parachains.collator]
  name = "some-collator"
  command = "parachain-template-node"
  ws_port = 8802
  rpc_port = 8082
  args = [ "-lparachain=debug,runtime=debug" ]
```

3. Yes, the relay chain stops at block 30 if I do not include a parachain in zombienet config. When including a parachain, the parachain stops on block 9.

I tried running a `v0.9.29` parachain on a `v0.9.36` relaychain and got the following `double free or corruption (out)`.


[parachain.log](https://github.com/paritytech/cumulus/files/10310357/parachain.log)
[relaychain.log](https://github.com/paritytech/cumulus/files/10310358/relaychain.log)
